# This workflow will do a clean install of node dependencies, cache/restore them, build the source code, and clean the repository leaving only the build

name: Builder

on:
  push:
    branches:
      - main

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    # build app
    - run: npm ci
    - run: npm run build
    - run: echo "www.rudrecciah.dev" > ./build/CNAME
    # clean up build
    - run: mkdir ./.build/
    - run: mv ./build ./.build -f
    - run: shopt -u dotglob
    - run: rm * -r
    - run: mv ./build . -f
    # commit and push to main to be deployed with pages
    - run: git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - run: git config --local user.name "github-actions[bot]"
    - run: git add ./
    - run: git commit -m "Built App"
    - run: git push
    
