# This workflow will:
#   Installs dependencies
#   Builds app
#   Deploys app
#   Cleans working directory and pushes build to main

name: Builder

on:
  push:
    branches:
      - main
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build
      run: |
        npm ci
        npm run build
        echo "www.rudrecciah.dev" > ./build/CNAME
        rm -rf ./temp
        mkdir ./temp
        cp ./build/* ./temp -r
    # deploy app
    - name: Deploy
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: './temp'
        destination-github-username: 'RudRecciah'
        destination-repository-name: 'rudrecciah.github.io'
        user-email: "41898282+github-actions[bot]@users.noreply.github.com"
        user-name: "github-actions[bot]"
        commit-message: "Deployed App"
        target-branch: "gh-pages"
    # commit and push to main to be deployed with pages
    - name: Cleanup
      run: |
        rm ./temp -r
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./
        git commit -m "Built App"
        git push
