# This workflow will:
#   Clean install of node dependencies
#   Cache/restore them
#   Build the source code
#   Deploy the source code
#   Clean the repository leaving only the build

name: Builder

on:
  push:
    branches:
      - main
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Create Build
      run: |
        npm ci
        npm run build
        echo "www.rudrecciah.dev" > ./build/CNAME
    # deploy app
    - name: Create Production
      run: |
        rm -rf ./temp
        mkdir ./temp
        git clone -b gh-pages https://github.com/RudRecciah/rudrecciah.github.io.git ./temp
        cd ./temp && shopt -u dotglob
        cd ./temp && rm *
        cd ../
        ls
        cp ./build/* ./temp -r
    - name: Deploy Production
      run: |
        ls
        cd ./temp && git add .
        ls
        cd ./temp && git commit -m "Deployed App"
        cd ./temp && git push
        rm ./temp -r
    # commit and push to main to be deployed with pages
    - name: Deploy Build
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./
        git commit -m "Built App"
        git push gh-pages
