# This workflow:
#  - Installs dependencies
#  - Builds app
#  - Deploys app
#  - Pushes build to main
#  - Checks out to dev and prepares it for more development

name: Builder

on:
  push:
    branches:
      - main
  workflow_dispatch:
      
jobs:

  build:
  
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [14.x]
        
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build and bundle plugins
      run: |
        rm -rf ./build
        rm -rf ./temp
        npm ci
        npm run build
        echo "www.rudrecciah.dev" > ./build/CNAME
        mkdir ./temp
        cp ./build/* ./temp -r
        mkdir -p ./plugins
        rsync -a ./plugins/ ./temp/
    - name: Deploy app to gh-pages
      id: push_directory
      uses: cpina/github-action-push-to-another-repository@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source-directory: './temp'
        destination-github-username: 'RudRecciah'
        destination-repository-name: 'rudrecciah.github.io'
        user-email: "41898282+github-actions[bot]@users.noreply.github.com"
        user-name: "github-actions[bot]"
        commit-message: "Deployed App"
        target-branch: "gh-pages"
    - name: Push build to main
      run: |
        rm -rf ./temp
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./
        git commit -m "Built App" --allow-empty
        git push
    - name: Sync main with dev
      uses: devmasx/merge-branch@v1.3.1
      with:
        type: now
        from_branch: main
        target_branch: dev
        github_token: ${{ github.token }}
    - name: Checkout to dev
      uses: actions/checkout@v2.3.4
      with:
        ref: "dev"
    - name: Cleanup dev
      run: |
        rm -rf ./build
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add ./
        git commit -m "Cleaned up dev" --allow-empty
        git push
